server:
  port: 8080

# spring.profiles has been deprecated
spring:
  redis:
    host: 127.0.0.1
    port: 6301
    database: 0
#    cluster:
#      nodes:
#        - 127.0.0.0:6301
#        - 127.0.0.0:6302
#        - 127.0.0.0:6303
#        - 127.0.0.0:6304
#        - 127.0.0.0:6305
#        - 127.0.0.0:6306
#      max-redirects: 3  # 获取失败 最大重定向次数
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle:  5     # 连接池中的最小空闲连接
    timeout: 6000  # 连接超时时长（毫秒）


---
spring:
  config:
    activate:
      on-profile: redis-jedis
  redis:
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    cluster:
      nodes:
        - 127.0.0.0:6301
        - 127.0.0.0:6302
        - 127.0.0.0:6303
        - 127.0.0.0:6304
        - 127.0.0.0:6305
        - 127.0.0.0:6306
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接


---
spring:
  config:
    activate:
      on-profile: redis-lettuce
  redis:
    timeout: 6000ms
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 127.0.0.0:6301
        - 127.0.0.0:6302
        - 127.0.0.0:6303
        - 127.0.0.0:6304
        - 127.0.0.0:6305
        - 127.0.0.0:6306
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

